import { Stethoscope, Wrench, Home, Scale, Hammer, GraduationCap, Utensils, Car, ShoppingBag } from "lucide-react";

export interface Business {
  id: number;
  name: string;
  nameAr: string;
  category: string;
  subcategory: string;
  subcategoryAr: string;
  lat: number;
  lng: number;
  rating: number;
  distance: string;
  phone: string;
  address: string;
  addressAr: string;
}

export interface Category {
  id: string;
  nameEn: string;
  nameAr: string;
  icon: any;
  color: string;
  subcategories: { id: string; nameEn: string; nameAr: string }[];
}

export const categories: Category[] = [
  {
    id: "all",
    nameEn: "All Services",
    nameAr: "جميع الخدمات",
    icon: ShoppingBag,
    color: "from-gray-500 to-gray-700",
    subcategories: [],
  },
  {
    id: "medical",
    nameEn: "Medical",
    nameAr: "طبي",
    icon: Stethoscope,
    color: "from-blue-500 to-blue-700",
    subcategories: [
      { id: "dentist", nameEn: "Dentist", nameAr: "طبيب أسنان" },
      { id: "general", nameEn: "General Practice", nameAr: "طب عام" },
      { id: "pharmacy", nameEn: "Pharmacy", nameAr: "صيدلية" },
      { id: "specialist", nameEn: "Specialist", nameAr: "أخصائي" },
    ],
  },
  {
    id: "services",
    nameEn: "Services",
    nameAr: "خدمات",
    icon: Wrench,
    color: "from-orange-500 to-red-500",
    subcategories: [
      { id: "carpenter", nameEn: "Carpenter", nameAr: "نجار" },
      { id: "plumber", nameEn: "Plumber", nameAr: "سباك" },
      { id: "electrician", nameEn: "Electrician", nameAr: "كهربائي" },
      { id: "painter", nameEn: "Painter", nameAr: "دهان" },
    ],
  },
  {
    id: "realestate",
    nameEn: "Real Estate",
    nameAr: "عقارات",
    icon: Home,
    color: "from-purple-500 to-pink-500",
    subcategories: [
      { id: "apartments", nameEn: "Apartments", nameAr: "شقق" },
      { id: "villas", nameEn: "Villas", nameAr: "فيلات" },
      { id: "commercial", nameEn: "Commercial", nameAr: "تجاري" },
      { id: "land", nameEn: "Land", nameAr: "أراضي" },
    ],
  },
  {
    id: "legal",
    nameEn: "Legal",
    nameAr: "قانوني",
    icon: Scale,
    color: "from-indigo-500 to-purple-600",
    subcategories: [
      { id: "lawyer", nameEn: "Lawyer", nameAr: "محامي" },
      { id: "notary", nameEn: "Notary", nameAr: "كاتب عدل" },
      { id: "consultant", nameEn: "Legal Consultant", nameAr: "مستشار قانوني" },
    ],
  },
  {
    id: "engineering",
    nameEn: "Engineering",
    nameAr: "هندسة",
    icon: Hammer,
    color: "from-yellow-500 to-orange-600",
    subcategories: [
      { id: "civil", nameEn: "Civil Engineering", nameAr: "هندسة مدنية" },
      { id: "architect", nameEn: "Architecture", nameAr: "معماري" },
      { id: "mechanical", nameEn: "Mechanical", nameAr: "ميكانيكا" },
    ],
  },
  {
    id: "education",
    nameEn: "Education",
    nameAr: "تعليم",
    icon: GraduationCap,
    color: "from-green-500 to-teal-500",
    subcategories: [
      { id: "tutor", nameEn: "Private Tutor", nameAr: "مدرس خصوصي" },
      { id: "school", nameEn: "School", nameAr: "مدرسة" },
      { id: "training", nameEn: "Training Center", nameAr: "مركز تدريب" },
    ],
  },
  {
    id: "food",
    nameEn: "Food & Dining",
    nameAr: "طعام ومطاعم",
    icon: Utensils,
    color: "from-red-500 to-pink-500",
    subcategories: [
      { id: "restaurant", nameEn: "Restaurant", nameAr: "مطعم" },
      { id: "cafe", nameEn: "Café", nameAr: "كافيه" },
      { id: "bakery", nameEn: "Bakery", nameAr: "مخبز" },
    ],
  },
  {
    id: "automotive",
    nameEn: "Automotive",
    nameAr: "سيارات",
    icon: Car,
    color: "from-gray-600 to-gray-800",
    subcategories: [
      { id: "repair", nameEn: "Car Repair", nameAr: "إصلاح سيارات" },
      { id: "wash", nameEn: "Car Wash", nameAr: "غسيل سيارات" },
      { id: "parts", nameEn: "Auto Parts", nameAr: "قطع غيار" },
    ],
  },
];

export const mockBusinesses: Business[] = [
  {
    id: 1,
    name: "Dr. Ahmed Clinic",
    nameAr: "عيادة الدكتور أحمد",
    category: "medical",
    subcategory: "dentist",
    subcategoryAr: "طبيب أسنان",
    lat: 30.0444,
    lng: 31.2357,
    rating: 4.8,
    distance: "2.1 km",
    phone: "01012345678",
    address: "15 Tahrir St, Cairo",
    addressAr: "15 شارع التحرير، القاهرة",
  },
  {
    id: 2,
    name: "Mansoura Carpenter",
    nameAr: "نجار المنصورة",
    category: "services",
    subcategory: "carpenter",
    subcategoryAr: "نجار",
    lat: 31.0419,
    lng: 31.3785,
    rating: 4.6,
    distance: "4.5 km",
    phone: "01087654321",
    address: "28 El-Gomhoreya St, Mansoura",
    addressAr: "28 شارع الجمهورية، المنصورة",
  },
  {
    id: 3,
    name: "Cairo Legal Consultants",
    nameAr: "مستشارو القاهرة القانونيون",
    category: "legal",
    subcategory: "lawyer",
    subcategoryAr: "محامي",
    lat: 30.0626,
    lng: 31.2497,
    rating: 4.9,
    distance: "1.8 km",
    phone: "01098765432",
    address: "42 Kasr El Nil St, Cairo",
    addressAr: "42 شارع قصر النيل، القاهرة",
  },
  {
    id: 4,
    name: "Alexandria Pharmacy",
    nameAr: "صيدلية الإسكندرية",
    category: "medical",
    subcategory: "pharmacy",
    subcategoryAr: "صيدلية",
    lat: 31.2001,
    lng: 29.9187,
    rating: 4.7,
    distance: "0.8 km",
    phone: "01054321098",
    address: "89 Horreya Ave, Alexandria",
    addressAr: "89 شارع الحرية، الإسكندرية",
  },
  {
    id: 5,
    name: "Elite Engineering",
    nameAr: "النخبة للهندسة",
    category: "engineering",
    subcategory: "civil",
    subcategoryAr: "هندسة مدنية",
    lat: 30.0131,
    lng: 31.2089,
    rating: 4.5,
    distance: "3.2 km",
    phone: "01076543210",
    address: "56 Salah Salem Rd, Cairo",
    addressAr: "56 طريق صلاح سالم، القاهرة",
  },
  {
    id: 6,
    name: "Nile Restaurant",
    nameAr: "مطعم النيل",
    category: "food",
    subcategory: "restaurant",
    subcategoryAr: "مطعم",
    lat: 30.0444,
    lng: 31.2357,
    rating: 4.4,
    distance: "1.5 km",
    phone: "01023456789",
    address: "Corniche El Nile, Cairo",
    addressAr: "كورنيش النيل، القاهرة",
  },
  {
    id: 7,
    name: "Expert Plumbing Services",
    nameAr: "خدمات السباكة الخبيرة",
    category: "services",
    subcategory: "plumber",
    subcategoryAr: "سباك",
    lat: 30.0330,
    lng: 31.2336,
    rating: 4.3,
    distance: "2.7 km",
    phone: "01065432109",
    address: "12 Ramses St, Cairo",
    addressAr: "12 شارع رمسيس، القاهرة",
  },
  {
    id: 8,
    name: "Premium Auto Care",
    nameAr: "العناية المتميزة بالسيارات",
    category: "automotive",
    subcategory: "repair",
    subcategoryAr: "إصلاح سيارات",
    lat: 30.0561,
    lng: 31.2394,
    rating: 4.7,
    distance: "3.9 km",
    phone: "01098761234",
    address: "78 Autostrad Rd, Cairo",
    addressAr: "78 طريق الأوتوستراد، القاهرة",
  },
  {
    id: 9,
    name: "Bright Future Academy",
    nameAr: "أكاديمية المستقبل المشرق",
    category: "education",
    subcategory: "tutor",
    subcategoryAr: "مدرس خصوصي",
    lat: 31.2156,
    lng: 29.9553,
    rating: 4.6,
    distance: "1.2 km",
    phone: "01087651234",
    address: "34 El-Horreya Rd, Alexandria",
    addressAr: "34 طريق الحرية، الإسكندرية",
  },
  {
    id: 10,
    name: "Downtown Apartments",
    nameAr: "شقق وسط المدينة",
    category: "realestate",
    subcategory: "apartments",
    subcategoryAr: "شقق",
    lat: 30.0444,
    lng: 31.2357,
    rating: 4.2,
    distance: "0.5 km",
    phone: "01056781234",
    address: "5 Talaat Harb St, Cairo",
    addressAr: "5 شارع طلعت حرب، القاهرة",
  },
  {
    id: 11,
    name: "Modern Electrician",
    nameAr: "الكهربائي الحديث",
    category: "services",
    subcategory: "electrician",
    subcategoryAr: "كهربائي",
    lat: 30.0871,
    lng: 31.3242,
    rating: 4.5,
    distance: "5.1 km",
    phone: "01034567890",
    address: "91 Nasr City, Cairo",
    addressAr: "91 مدينة نصر، القاهرة",
  },
  {
    id: 12,
    name: "Family Dental Care",
    nameAr: "رعاية الأسنان العائلية",
    category: "medical",
    subcategory: "dentist",
    subcategoryAr: "طبيب أسنان",
    lat: 30.0715,
    lng: 31.0214,
    rating: 4.9,
    distance: "6.8 km",
    phone: "01045678901",
    address: "120 Pyramids Rd, Giza",
    addressAr: "120 طريق الأهرام، الجيزة",
  },
];
